{"uuid": "e45d40ab-4430-4756-b49d-9e8396cb785d", "children": ["8f818296-2452-45e1-ae4a-b5ee6c682821", "942b9465-54ba-4a5c-9b7a-ee73429b0dd4", "4f62fd1d-77c1-4073-a786-957b20ede9b1", "5fe28467-8fb6-4e49-afa1-528a8c45982c"], "befores": [{"name": "_Module__pytest_setup_module", "status": "passed", "start": 1619518673712, "stop": 1619518673712}], "afters": [{"name": "_Module__pytest_setup_module::0", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')\n", "trace": "  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 474, in xunit_setup_module_fixture\n    _call_with_optional_argument(teardown_module, request.module)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\testcase\\Loginapi\\Find_Bind_Third_User_test.py\", line 66, in teardown_module\n    custid=PyMySQL().mysqlget(sql)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\utils\\pysql.py\", line 90, in mysqlget\n    cursor.execute(sql)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 170, in execute\n    result = self._query(query)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\cursors.py\", line 328, in _query\n    conn.query(q)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 517, in query\n    self._affected_rows = self._read_query_result(unbuffered=unbuffered)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 732, in _read_query_result\n    result.read()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 1075, in read\n    first_packet = self.connection._read_packet()\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 657, in _read_packet\n    packet_header = self._read_bytes(4)\n  File \"C:\\Users\\chenping\\PycharmProjects\\apitest\\venv\\lib\\site-packages\\pymysql\\connections.py\", line 707, in _read_bytes\n    CR.CR_SERVER_LOST, \"Lost connection to MySQL server during query\")\n"}, "start": 1619518675043, "stop": 1619518675222}], "start": 1619518673712, "stop": 1619518675222}